// SPDX-License-Identifier: GPL-2.0-only
/*
 * Waveshare ESP32-S3-Touch-LCD-3.49 V2 ASoC machine driver
 *
 * Links the ESP32-S3 I2S0 CPU DAI with the ES8311 codec (playback,
 * mainline driver) and the ES7210 ADC (capture, fork driver), and
 * drives the NS4150B amplifier enable line on TCA9554 EXIO7.
 *
 * MCLK, BCLK and frame clock are generated by I2S0. The machine hw_params
 * callback establishes MCLK before codec hw_params runs.
 */

#include <linux/gpio/consumer.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/overflow.h>
#include <linux/platform_device.h>

#include <sound/pcm.h>
#include <sound/soc.h>

struct esp32s3_audio_priv {
	struct gpio_desc *pa_gpio; /* NS4150B enable, TCA9554 EXIO7 */
};

SND_SOC_DAILINK_DEFS(playback,
	DAILINK_COMP_ARRAY(COMP_CPU("esp32s3-i2s0")),
	DAILINK_COMP_ARRAY(COMP_CODEC("es8311.0-0018", "es8311")),
	DAILINK_COMP_ARRAY(COMP_PLATFORM("esp32s3-i2s0")));

SND_SOC_DAILINK_DEFS(capture,
	DAILINK_COMP_ARRAY(COMP_CPU("esp32s3-i2s0")),
	DAILINK_COMP_ARRAY(COMP_CODEC("es7210.0-0040", "es7210")),
	DAILINK_COMP_ARRAY(COMP_PLATFORM("esp32s3-i2s0")));

static int esp32s3_audio_amp_event(struct snd_soc_dapm_widget *widget,
				   struct snd_kcontrol *control, int event)
{
	struct snd_soc_card *card = snd_soc_dapm_to_card(widget->dapm);
	struct esp32s3_audio_priv *priv = snd_soc_card_get_drvdata(card);

	if (!priv->pa_gpio)
		return 0;

	switch (event) {
	case SND_SOC_DAPM_POST_PMU:
		gpiod_set_value_cansleep(priv->pa_gpio, 1);
		break;
	case SND_SOC_DAPM_PRE_PMD:
		gpiod_set_value_cansleep(priv->pa_gpio, 0);
		break;
	default:
		return -EINVAL;
	}

	return 0;
}

static int esp32s3_audio_hw_params(struct snd_pcm_substream *substream,
				   struct snd_pcm_hw_params *params)
{
	struct snd_soc_pcm_runtime *rtd = snd_soc_substream_to_rtd(substream);
	struct snd_soc_dai *cpu_dai = snd_soc_rtd_to_cpu(rtd, 0);
	struct snd_soc_dai *codec_dai = snd_soc_rtd_to_codec(rtd, 0);
	unsigned int mclk;
	int ret;

	if (check_mul_overflow(params_rate(params), 256U, &mclk))
		return -EOVERFLOW;

	ret = snd_soc_dai_set_sysclk(cpu_dai, 0, mclk, SND_SOC_CLOCK_OUT);
	if (ret)
		return ret;

	return snd_soc_dai_set_sysclk(codec_dai, 0, mclk,
				      SND_SOC_CLOCK_IN);
}

static const struct snd_soc_ops esp32s3_audio_ops = {
	.hw_params = esp32s3_audio_hw_params,
};

static const struct snd_soc_dapm_widget esp32s3_audio_widgets[] = {
	SND_SOC_DAPM_OUT_DRV_E("Amplifier", SND_SOC_NOPM, 0, 0, NULL, 0,
			       esp32s3_audio_amp_event,
			       SND_SOC_DAPM_POST_PMU | SND_SOC_DAPM_PRE_PMD),
	SND_SOC_DAPM_SPK("Speaker", NULL),
};

static const struct snd_soc_dapm_route esp32s3_audio_routes[] = {
	{ "Amplifier", NULL, "OUT" },
	{ "Speaker", NULL, "Amplifier" },
};

static struct snd_soc_dai_link esp32s3_audio_dai_links[] = {
	{
		.name = "playback",
		.stream_name = "Playback",
		.dai_fmt = SND_SOC_DAIFMT_I2S | SND_SOC_DAIFMT_NB_NF |
			   SND_SOC_DAIFMT_CBC_CFC,
		.ops = &esp32s3_audio_ops,
		SND_SOC_DAILINK_REG(playback),
	},
	{
		.name = "capture",
		.stream_name = "Capture",
		.dai_fmt = SND_SOC_DAIFMT_I2S | SND_SOC_DAIFMT_NB_NF |
			   SND_SOC_DAIFMT_CBC_CFC,
		.ops = &esp32s3_audio_ops,
		SND_SOC_DAILINK_REG(capture),
	},
};

static struct snd_soc_card esp32s3_audio_card = {
	.name = "esp32s3-audio",
	.owner = THIS_MODULE,
	.dai_link = esp32s3_audio_dai_links,
	.num_links = ARRAY_SIZE(esp32s3_audio_dai_links),
	.dapm_widgets = esp32s3_audio_widgets,
	.num_dapm_widgets = ARRAY_SIZE(esp32s3_audio_widgets),
	.dapm_routes = esp32s3_audio_routes,
	.num_dapm_routes = ARRAY_SIZE(esp32s3_audio_routes),
};

static int esp32s3_audio_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct esp32s3_audio_priv *priv;
	struct snd_soc_card *card = &esp32s3_audio_card;

	priv = devm_kzalloc(dev, sizeof(*priv), GFP_KERNEL);
	if (!priv)
		return -ENOMEM;

	/* Optional NS4150B amplifier enable (TCA9554 EXIO7) */
	priv->pa_gpio = devm_gpiod_get_optional(dev, "pa", GPIOD_OUT_LOW);
	if (IS_ERR(priv->pa_gpio))
		return dev_err_probe(dev, PTR_ERR(priv->pa_gpio),
				     "failed to get PA GPIO\n");

	card->dev = dev;
	snd_soc_card_set_drvdata(card, priv);

	return devm_snd_soc_register_card(dev, card);
}

static const struct of_device_id esp32s3_audio_of_match[] = {
	{ .compatible = "waveshare,esp32s3-audio" },
	{ }
};
MODULE_DEVICE_TABLE(of, esp32s3_audio_of_match);

static struct platform_driver esp32s3_audio_driver = {
	.driver = {
		.name = "esp32s3-audio",
		.of_match_table = esp32s3_audio_of_match,
	},
	.probe = esp32s3_audio_probe,
};
module_platform_driver(esp32s3_audio_driver);

MODULE_DESCRIPTION("Waveshare ESP32-S3-Touch-LCD-3.49 V2 ASoC machine driver");
MODULE_AUTHOR("ESP32-S3 Linux project");
MODULE_LICENSE("GPL");
