# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SND_SOC_ESP32S3_I2S) += i2s-esp32s3.o
obj-$(CONFIG_SND_SOC_ESP32S3_I2S_KUNIT_TEST) += i2s-esp32s3-test.o
obj-$(CONFIG_SND_SOC_ES7210) += es7210.o
obj-$(CONFIG_SND_SOC_ES7210_KUNIT_TEST) += es7210-test.o
obj-$(CONFIG_SND_SOC_ESP32S3_AUDIO) += esp32s3-audio.o
